services:
  api:
    image: xklaky35/welcome_page_api
    build: ./api
    ports:
      - 7878:8080
    volumes:
      - ./config.json:/config.json
      - ./.env:/.env
      - type: bind
        source: ./api/data/data.json
        target: /data/data.json
  updater:
    image: xklaky35/api_updater
    build: ./api_updater
    volumes:
      - ./config.json:/config.json
      - ./.env:/.env
