services:
  api:
    image: xklaky35/server-api
    build: ./api
    ports:
      - 7878:3000
    volumes:
      - ./welcome-page-api/config.json:/welcome-page-api/config.json
      - ./api/.env:/.env
      - type: bind
        source: ./welcome-page-api/data.json
        target: /welcome-page-api/data.json
      - type: bind
        source: ./welcome-page-api/logs.log
        target: /welcome-page-api/logs.log
  updater:
    image: xklaky35/api-updater
    build: ./api-updater
    volumes:
      - ./welcome-page-api/config.json:/config.json
      - ./api/.env:/.env
