services:
  api:
    image: xklaky35/welcome_page_api
    build: ./
    ports:
      - 7878:8080
    volumes:
      - type: bind
        source: ./.env
        target: /.env
      - type: bind
        source: ./data/config.json
        target: /data/config.json
